spring.datasource.url=jdbc:postgresql://8.219.139.67:5436/document_engine
spring.datasource.username=document_engine
spring.datasource.password=document_engine
#spring.datasource.url=jdbc:postgresql://localhost:5432/document_engine
#spring.datasource.username=postgres
#spring.datasource.password=2003

logging.level.kh.com.kshrd.docengine=debug
jwt.secret=javainuse
mybatis.type-handlers-package=kh.com.kshrd.docengine.configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=menglotkheng@gmail.com
spring.mail.password=ulrvxmoaeovffpgv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
