spring.datasource.url=jdbc:postgresql://localhost:5432/DocEngine
spring.datasource.username=postgres
spring.datasource.password=Menglot2002
#spring.profiles.active=dev
logging.level.kh.com.kshrd.docengine=debug
jwt.secret=javainuse
